AWSTemplateFormatVersion: "2010-09-09"
Description: "stackName: {Prefix}-{Env}-codepipeline. AWS::CodeBuild::Project AWS::CodePipeline::Pipeline"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Name Configuration
        Parameters:
          - Prefix
          - Env
          - Project
      - Label:
          default: GitHub Configuration
        Parameters:
          - GitHubDeployBranch

Parameters:
  Prefix:
    Type: String
    Description: AWS resource version management prefix
    Default: v1
  Env:
    Type: String
    Description: Project environment
    AllowedValues: [dev, prd]
  Project:
    Type: String
    Description: Project Name
    Default: example
  GitHubDeployBranch:
    Type: String
    Description: GitHub deploy branch
    Default: main

Mappings:
  ImportValueMap:
    CodeBuildServiceRole:
      Arn: ecs-codebuild-service-role-arn
    CodePipelineServiceRole:
      Arn: ecs-codepipeline-service-role-arn
    CodePipelineArtifactsS3:
      BucketName: codepipeline-artifacts-s3-bucket-name
    CodestarConnection:
      Arn: codestar-github-connection-arn
  ServiceMap:
    GitHub:
      Organization: kita21
      Repository: iac-templates
    BuildSpec:
      File: sample-app/ts-api/buildspec.yml
  AWSParameterMap:
    RetentionInDays:
      dev: 7
      prd: 180
    CodeBuild: # https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/build-env-ref-available.html
      Image: aws/codebuild/standard:7.0

Resources:
  CWLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/deploy-codebuild/${Prefix}-${Env}-${Project}"
      RetentionInDays: !FindInMap [AWSParameterMap, RetentionInDays, !Ref Env]
      Tags:
        - Key: cfn-stackname
          Value: !Sub ${AWS::StackName}

  ECSDeployCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${Prefix}-${Env}-${Project}-ecs-deploy-codebuild
      Description: ${Prefix}-${Env}-${Project}-ecs-deploy-codebuild
      ServiceRole:
        Fn::ImportValue: !FindInMap [ImportValueMap, CodeBuildServiceRole, Arn]
      QueuedTimeoutInMinutes: 30
      TimeoutInMinutes: 30
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_DOCKER_LAYER_CACHE
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref CWLogGroup
          Status: ENABLED
      Source:
        BuildSpec: !FindInMap [ServiceMap, BuildSpec, File]
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !FindInMap [AWSParameterMap, CodeBuild, Image]
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ENV
            Type: PLAINTEXT
            Value: !Ref Env
          - Name: PREFIX
            Type: PLAINTEXT
            Value: !Ref Prefix
          - Name: PROJECT
            Type: PLAINTEXT
            Value: !Ref Project
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
          - Name: AWS_REGION_NAME
            Type: PLAINTEXT
            Value: !Ref AWS::Region

  ECSDeployCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${Prefix}-${Env}-${Project}-ecs-codepipeline
      RoleArn:
        Fn::ImportValue: !FindInMap [ImportValueMap, CodePipelineServiceRole, Arn]
      ArtifactStore:
        Type: S3
        Location:
          Fn::ImportValue: !FindInMap [ImportValueMap, CodePipelineArtifactsS3, BucketName]
      Stages:
        - Name: Source
          Actions:
            - Name: SourceStage
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              Configuration:
                FullRepositoryId: !Sub
                  - ${GitHubOrganization}/${GitHubRepository}
                  - GitHubOrganization: !FindInMap [ServiceMap, GitHub, Organization]
                    GitHubRepository: !FindInMap [ServiceMap, GitHub, Repository]
                ConnectionArn:
                  Fn::ImportValue: !FindInMap [ImportValueMap, CodestarConnection, Arn]
                BranchName: !Ref GitHubDeployBranch
                DetectChanges: false
                OutputArtifactFormat: CODE_ZIP
              RunOrder: 1
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: Build
          Actions:
            - Name: BuildStage
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref ECSDeployCodeBuildProject
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: DeployStage
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: ECS
              Configuration:
                ClusterName:
                  Fn::ImportValue: !Sub ${Prefix}-${Env}-${Project}-ecs-cluster-name
                ServiceName:
                  Fn::ImportValue: !Sub ${Prefix}-${Env}-${Project}-ecs-service-name
                FileName: imagedefinitions.json
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
